#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v3
# autospec commit: 750e50d
#
Name     : pypi-pynsist
Version  : 2.8
Release  : 17
URL      : https://files.pythonhosted.org/packages/99/e0/b1b797633a71fadb5e37b44b69a707bf1f3108f1922d25bbb82d320af0cd/pynsist-2.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/99/e0/b1b797633a71fadb5e37b44b69a707bf1f3108f1922d25bbb82d320af0cd/pynsist-2.8.tar.gz
Summary  : Build NSIS installers for Python applications.
Group    : Development/Tools
License  : MIT
Requires: pypi-pynsist-bin = %{version}-%{release}
Requires: pypi-pynsist-license = %{version}-%{release}
Requires: pypi-pynsist-python = %{version}-%{release}
Requires: pypi-pynsist-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Pynsist is a tool to build Windows installers for your Python applications. The
installers bundle Python itself, so you can distribute your application to
people who don't have Python installed.

%package bin
Summary: bin components for the pypi-pynsist package.
Group: Binaries
Requires: pypi-pynsist-license = %{version}-%{release}

%description bin
bin components for the pypi-pynsist package.


%package license
Summary: license components for the pypi-pynsist package.
Group: Default

%description license
license components for the pypi-pynsist package.


%package python
Summary: python components for the pypi-pynsist package.
Group: Default
Requires: pypi-pynsist-python3 = %{version}-%{release}

%description python
python components for the pypi-pynsist package.


%package python3
Summary: python3 components for the pypi-pynsist package.
Group: Default
Requires: python3-core
Provides: pypi(pynsist)
Requires: pypi(distlib)
Requires: pypi(jinja2)
Requires: pypi(requests)
Requires: pypi(requests_download)
Requires: pypi(yarg)

%description python3
python3 components for the pypi-pynsist package.


%prep
%setup -q -n pynsist-2.8
cd %{_builddir}/pynsist-2.8
pushd ..
cp -a pynsist-2.8 buildavx2
popd
pushd ..
cp -a pynsist-2.8 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707133644
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd
pushd ../buildapx/
CC=gcc-14
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pynsist
cp %{_builddir}/pynsist-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pynsist/744d155856cad539df9e13c3ed4a29f3539d3433 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
pushd ../buildapx/
CC=gcc-14
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 -mapxf -mavx10.1 "
python3 -m installer --destdir=%{buildroot}-va dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-console-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-datetime-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-debug-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-errorhandling-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-file-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-file-l1-2-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-file-l2-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-handle-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-heap-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-interlocked-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-libraryloader-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-localization-l1-2-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-memory-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-namedpipe-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-processenvironment-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-processthreads-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-processthreads-l1-1-1.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-profile-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-rtlsupport-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-string-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-synch-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-synch-l1-2-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-sysinfo-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-timezone-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-core-util-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-conio-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-convert-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-environment-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-filesystem-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-heap-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-locale-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-math-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-multibyte-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-private-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-process-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-runtime-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-stdio-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-string-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-time-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/api-ms-win-crt-utility-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x64/ucrtbase.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-console-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-datetime-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-debug-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-errorhandling-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-file-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-file-l1-2-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-file-l2-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-handle-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-heap-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-interlocked-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-libraryloader-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-localization-l1-2-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-memory-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-namedpipe-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-processenvironment-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-processthreads-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-processthreads-l1-1-1.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-profile-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-rtlsupport-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-string-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-synch-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-synch-l1-2-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-sysinfo-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-timezone-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-core-util-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-conio-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-convert-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-environment-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-filesystem-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-heap-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-locale-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-math-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-multibyte-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-private-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-process-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-runtime-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-stdio-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-string-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-time-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/api-ms-win-crt-utility-l1-1-0.dll
rm -f %{buildroot}*/usr/lib/python3.12/site-packages/nsist/msvcrt/x86/ucrtbase.dll
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pynsist

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pynsist/744d155856cad539df9e13c3ed4a29f3539d3433

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
